server:
  port: 8080

spring:
  datasource:
    driver: org.postgresql.postgresql
    url: jdbc:postgresql://localhost:5432/fleet_vehicles?stringtype=unspecified
    username: agence
    password: agence
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
