version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: agence
      POSTGRES_PASSWORD: agence
      POSTGRES_DB: fleet_vehicles